label {
	text = cmd[update:1000] echo "<span>$(date +"%H:%M")</span>"
	color = rgba(255, 255, 255, 0.8)
	font_size = 120
	font_family = Cascadia Code
	position = 0, 350
	halign = center
	valign = center
}

animations {
	enabled = true
	bezier = linear, 1, 1, 0, 0
	animation = fadeIn, 1, 5, linear
	animation = fadeOut, 1, 5, linear
	animation = inputFieldDots, 1, 2, linear
	animation = inputFieldColors, 1, 2, linear
}

input-field {
	monitor = 
	size    = 20%, 5%
	outline_thickness = 2
	inner_color = rgba(0, 0, 0, 0.0)

	hide_input  = true

	outer_color = rgba(33ccffee) rgba(00ff99ee)
	check_color = rgba(00ff99ee) rgba(ff6633ee)
	fail_color  = rgba(ff6633ee) rgba(ff0066ee)

	font_color    = rgb(143, 143, 143)
	fade_on_empty = false
	rounding      = 15

	position = 0, -20
	halign   = center
	valign   = center
}

